version: 0.2

phases:
  install:
    # runtime-versions:
    #   nodejs: latest # Only if your Terraform project needs Node.js
    commands:
      - echo Installing Terraform
      - curl -O https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip
      - unzip terraform_1.3.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo Initializing Terraform
      - terraform init

  build:
    commands:
      - echo Running Terraform plan
      - terraform plan -out=tfplan
      - echo Applying Terraform configuration
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo Terraform deployment completed

artifacts:
  files:
    - '**/*'
  discard-paths: yes